### ISSUE TITLE
Support of runes

### ISSUE THREAD

**Issue by reyzor1991** [reyzor1991/pf2e-eidolon-helper#11]
- Your eidolon gains item bonuses to Perception and skills from any magical items that you have invested.

- Your eidolon's Strikes benefit from the fundamental and property runes on your handwraps of mighty blows. Alternatively, you can Invest a magic weapon (even though magic weapons can't normally be Invested) to share its fundamental and property runes with your eidolon. You share these benefits only while you're holding the weapon, and you can have no more than one weapon invested in this way at a time. In either case, the eidolon gains only the benefits that can apply to its attacks, with the same limitations noted in handwraps of mighty blows.

**Comment by digitalshadowhawk** [comment]
just tried this setting and it doesn't work for the handwraps, haven't tried it for anything else

even tried unlinking and relinking the summoner and their eidolon, no luck

**Comment by reyzor1991** [comment]
Feature not finished yet, only resilient rune (armor)
