### ISSUE TITLE
[Bug] Spellcasting Matching not Working

### ISSUE THREAD

**Issue by ChasarooniZ** [reyzor1991/pf2e-eidolon-helper#12]
As title, spellcasting bonus isn't applying over to eidelon

**Comment by reyzor1991** [comment]
<img width="1099" alt="image" src="https://github.com/reyzor1991/pf2e-eidolon-helper/assets/6688366/f19b2dcf-fd15-4806-bb51-83430cd511ee">

When eidolon post spell dc is get from summoner.

Maybe setting is off?

**Comment by ChasarooniZ** [comment]
Hmmm, I'll check again and report back
