### ISSUE TITLE
[bug] Module is reference incorrectly

### ISSUE THREAD

**Issue by bLanark** [reyzor1991/pf2e-eidolon-helper#13]
In the current version, on a fresh install with only CC added, the share HP was not working. Console log reported the following error: 
![image](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/4310912/3e87fc0b-e0ce-4c14-9eca-88a6e3918b96)

Looking at the module JS function, I believe it should be referenced pf2e-eidolon-helper instead of all one word. 

![image](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/4310912/33545aa5-4883-410f-95c4-4e5d6ca16511)

Other parts of the module seem to work, with the hypons, its just when they aren't there it all breaks.

![image](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/4310912/154fdb51-77b1-40f5-aea5-f3dc40d15b45)

Can you take a look and put out a bug fix please?

**Comment by reyzor1991** [comment]
Check ```game.pf2eeidolonhelper``` in console. Looks like moodule not initialized

**Comment by bLanark** [comment]
Yep you are right, I didn't have the libWrapper module enabled, its now working when I installed that. Didn't notice the error message about the module.
