### ISSUE TITLE
Extend Boost macro defaults to wrong DC

### ISSUE THREAD

**Issue by Qenthel94** [reyzor1991/pf2e-eidolon-helper#2]
When using the extend boost macro from a level 2 summoner on a level 2 eidolon the DC defaults to 21, instead of the standard difficulty DC for level 2, which should be 16.
![Screenshot 2023-09-15 003952](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/87117602/b1dd1c23-22da-4903-adba-913594a095eb)

**Comment by reyzor1991** [comment]
Fixed 0.0.7
