### ISSUE TITLE
Canceling Extend Boost Macro pop-up applies reinforce eidolon effect and rolls dice with no DC

### ISSUE THREAD

**Issue by Qenthel94** [reyzor1991/pf2e-eidolon-helper#3]
If you press the cancel button on the extend boost macro pop-up, it will apply reinforce eidolon spell effect and roll dice against no DC. 
Closing the pop-up with the "X" does not cause this issue.
![Screenshot 2023-09-15 011737](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/87117602/e506f130-fccd-494e-b2fd-37c5d45620a0)
![Screenshot 2023-09-15 011712](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/87117602/0afee027-2afd-47e3-b380-4fc356911ace)

**Comment by reyzor1991** [comment]
Fixed
