### ISSUE TITLE
Extend Boost macro does not consume a focus point on success

### ISSUE THREAD

**Issue by Qenthel94** [reyzor1991/pf2e-eidolon-helper#4]
![Screenshot 2023-09-30 111158](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/87117602/da0f2326-499a-4baf-95bd-293e224295ba)

**Comment by Qenthel94** [comment]
![Screenshot 2023-09-30 111343](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/87117602/f52ab913-f412-437b-89a0-d8918b143775)

**Comment by reyzor1991** [comment]
Done
