### ISSUE TITLE
Extend boost focus point usage

### ISSUE THREAD

**Issue by ghost** [reyzor1991/pf2e-eidolon-helper#8]
Hi

Currently it seems that Extend Boost is using up a focus point on a crit failure - this doesn't appear to be intended as it has no 'Critical Failure' entry per AoN.

**Comment by reyzor1991** [comment]
Because, there are no point as for failure

**Comment by ghost** [comment]
Yes from what I understand it is meant to use *0* points on failure or critical failure, but the module is currently subtracting a focus point on a critical failure. It is working as intended on a normal failure.

**Comment by reyzor1991** [comment]
Need to ask someone from Paizo because I found
`Failure won’t eat your Focus Point so you can retry every turn, but Critical Failure will consume the Focus Point so this will always be a frustrating gamble`

**Comment by ghost** [comment]
> Need to ask someone from Paizo because I found `Failure won’t eat your Focus Point so you can retry every turn, but Critical Failure will consume the Focus Point so this will always be a frustrating gamble`

Where is this from?
Extend Boost does not list a critical failure effect and per Core Rulebook pg. 445:
https://2e.aonprd.com/Rules.aspx?ID=319
"If a feat, magic item, spell, or other effect does not list a critical success or critical failure, treat is as an ordinary success or failure instead."

Unless there is an official source saying otherwise I would say per the current rules critical failure is the same as failure.

**Comment by reyzor1991** [comment]
Fixed

**Comment by ghost** [comment]
Perfect, thank you!
