### ISSUE TITLE
hitpoint linking not working?

### ISSUE THREAD

**Issue by zarmstrong** [reyzor1991/pf2e-eidolon-helper#9]
When I damage a linked summoner/eidolon, one of them gets hurt, but not the other, indicating the shared hitpoint pool isn't working.

v0.013 on pf2e 5.7.3  foundy v11.313
warp gate 1.19.0 enabled

**Comment by reyzor1991** [comment]
Setting option is on?

**Comment by reyzor1991** [comment]
<img width="536" alt="Screenshot 2023-10-24 at 18 29 54" src="https://github.com/reyzor1991/pf2e-eidolon-helper/assets/6688366/bdda0c9f-2805-4694-9012-8379803f5f2b">

**Comment by zarmstrong** [comment]
Well that is embarrassing. I had set them, but was playing with other settings and I guess another module reloaded foundry due to changes in its settings that wiped out all my other setting changes.

Thanks for forcing me to check this again! 🤦🏻‍♂️

**Comment by zarmstrong** [comment]
Ok I just tested. I ensured the settings were checked. Reloaded. Linked eidolon to summoner via macro then damaged eidolon. Summoner is at full HP, eidolon is not.

![image](https://github.com/reyzor1991/pf2e-eidolon-helper/assets/565269/ce04c94a-4df0-47b5-9626-b0516a24dc39)

**Comment by reyzor1991** [comment]
Could you sent me json files of eidolon and summoner I will retest localy

**Comment by zarmstrong** [comment]
[fvtt-Actor-bree-treewarmer-sUkOS0mwq4MwgBH4 (1).json](https://github.com/reyzor1991/pf2e-eidolon-helper/files/13121822/fvtt-Actor-bree-treewarmer-sUkOS0mwq4MwgBH4.1.json)
[fvtt-Actor-yelmys-aVAysQ6otHRy69Bq (1).json](https://github.com/reyzor1991/pf2e-eidolon-helper/files/13121823/fvtt-Actor-yelmys-aVAysQ6otHRy69Bq.1.json)

**Comment by zarmstrong** [comment]
I duplicated the eidolon, deleted its ancestry and recreated the eidolon ancestry and that seems to have fixed it. I think there is some incompatibility between older versions of eidolon characters.

**Comment by reyzor1991** [comment]
Maybe the issue was with class slug, in old version sometimes it's empty

**Comment by zarmstrong** [comment]
Yes, it is null in the example I uploaded. 

`"slug": null,`
